name: Mirror to Second Account

on:
  push:
    branches:
      - '*' 

jobs:
  git-mirror:
    if: github.repository == 'YOUR_USERNAME/YOUR_REPO_NAME'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false 

      - name: Push to Mirror
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # Force the use of the token for the destination
          git remote add mirror "https://SohailSomnath:${{ secrets.GIT_SYNC_TOKEN }}@github.com/SohailSomnath/A-S-Networking.git"
          
          git push mirror --all --force
          git push mirror --tags --force